### ISSUE TITLE
Add Share clipboard feature

### ISSUE THREAD

**Issue by M2ck** [DHM47/Native-Clip-Board#46]
It would be awesome if you can add a share clipboard feature (without require Xposed).

**Comment by DHM47** [comment]
Do you mean an option in the share menu that would add what you shared to the clipboard, or a share option in the three dot menu in the expanded view?

**Comment by M2ck** [comment]
Why not both! 
For example share directly a link retrieved by the clipboard via Pushbullet on my device or later share my clipboard via a share option in the three dot menu from the expanded view.
It would a real improvement for this app i think.

**Comment by DHM47** [comment]
This has been suggested by a few of my friends, but they were never able to convince me of doing it. Because they could not give me a scenario where sharing from the 3-dot menu would be useful.
So can you think of a scenario where someone would open the clipboard and use share, instead of simply going to the desired app, and open the clipboard there and paste it.

As for the share menu, that would be good, but I never did it because Google Drive has already added that option.So I might add it as an option.

**Comment by DHM47** [comment]
Share from clipboard to other apps has been added.

**Comment by M2ck** [comment]
Great, but I've noticed that doesn't work well in Native Clipboard. Share menu is behind clipboard and when I want close clipboard, Share menu also closes.
This happens only with Back button from navigation bar, works fine with hardware Back button.
